TestWebApplication/TestWebApplication/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TestWebApplication.Dto;
using TestWebApplication.Models;
using TestWebApplication.Services;

namespace TestWebApplication.Controllers
{
    public class CommentController : Controller
    {
        private readonly IAsyncCommentService<Comment> asyncCommentService;

        public CommentController(IAsyncCommentService<Comment> AsyncCommentService)
        {
            asyncCommentService = AsyncCommentService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllComments(int page = 1, string searchParam = "")
        {
            if (string.IsNullOrEmpty(searchParam))
            {
                return View("ViewAllComment", await asyncCommentService.GetAll(page));
            }
            else
            {
                return View("ViewAllComment", await asyncCommentService.SearchComment(page, searchParam));
            }

        }

        [HttpPost("PostComment")]
        public async Task<IActionResult> PostComment([FromForm] PostCommentDto postCommentsDto)
        {
            if (ModelState.IsValid)
            {
                await asyncCommentService.Create(postCommentsDto);
                return RedirectToAction("GetAllComments");
            }
            else
            {
                ViewBag.ModelState = ModelState;
                return View("ModelErrorPage");
            }
        }

        [HttpPost("PutComment")]
        public async Task<IActionResult> PutComment([FromForm] PutCommentDto putCommentsDto)
        {
            if (ModelState.IsValid)
            {
                await asyncCommentService.Update(putCommentsDto);
                return RedirectToAction("GetAllComments");
            }
            else
            {
                ViewBag.ModelState = ModelState;
                return View("ModelErrorPage");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            await asyncCommentService.Remove(id);
            return RedirectToAction("GetAllComments");
        }

    }
}

TestWebApplication/TestWebApplication/Controllers/ImgController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using TestWebApplication.Dto;
using TestWebApplication.Models;
using TestWebApplication.Services;

namespace TestWebApplication.Controllers
{
    public class ImgController : Controller
    {
        private readonly IAsyncImgService<Img> asyncImgService;

        public ImgController(IAsyncImgService<Img> AsyncImgService)
        {
            asyncImgService = AsyncImgService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllImgs(int page = 1)
        {
            return View("ViewAllImg", await asyncImgService.GetAll(page));
        }

        [HttpGet]
        public async Task<IEnumerable<int>> GetAllID()
        {
            return await asyncImgService.GetAllId();
        }

        public async Task<IActionResult> GetImage(int id)
        {
            return File(await asyncImgService.GetImage(id), "image/png");
        }

        [HttpPost("PostImg")]
        public async Task<IActionResult> PostImg([FromForm] PostImgDto postImgDto)
        {
            await asyncImgService.Create(postImgDto);
            return RedirectToAction("GetAllImgs");
        }

        [HttpPost("PutImg")]
        public async Task<IActionResult> PutImg([FromForm] PutImgDto putImgDto)
        {
            await asyncImgService.Update(putImgDto);
            return RedirectToAction("GetAllImgs");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await asyncImgService.Remove(id);
            return RedirectToAction("GetAllImgs");
        }

        public async Task<IActionResult> DeleteArrayItems([FromBody] DeleteArrayImgsDto items)
        {
            await asyncImgService.RemoveRange(items.Items);
            return RedirectToAction("GetAllImgs");
        }

        [HttpPost("PostExport")]
        public async Task<FileResult> PostExport()
        {
            return File(await asyncImgService.Export(), "application/json", "imgs.json");
        }

        [HttpPost("PostImport")]
        public async Task<IActionResult> PostImport([FromForm] IFormFile file)
        {
            await asyncImgService.Import(file);
            return RedirectToAction("GetAllImgs");
        }

    }
}

TestWebApplication/TestWebApplication/Pages/Shared/ModelErrorPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApplication.Pages.Shared
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TestWebApplication/TestWebApplication/Pages/Shared/ViewAllComment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApplication.Pages.Shared
{
    public class ViewAllCommentModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TestWebApplication/TestWebApplication/Pages/Shared/ViewAllImg.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApplication.Pages.Shared
{
    public class ViewAllImgModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TestWebApplication/TestWebApplication/Pages/Shared/ModelErrorPage.cshtml
@page
    @using System.Linq;
    @using System.Collections.Generic;
    @using Microsoft.AspNetCore.Mvc.ModelBinding;
@model TestWebApplication.Pages.Shared.IndexModel
@{
 List<string> GetErrorListFromModelState(ModelStateDictionary modelState)
        {
            var query = from state in modelState.Values
                        from error in state.Errors
                        select error.ErrorMessage;
            var errorList = query.ToList();
            return errorList;
        }
}
<div>
    @foreach (String u in GetErrorListFromModelState(ViewBag.ModelState))
    {
    <h4>@u</h4>
    }
</div>

TestWebApplication/TestWebApplication/Pages/Shared/ViewAllComment.cshtml
@using TestWebApplication.Models
@model IndexViewModel<Comment>


<div style="margin:20px;border:dotted">
    <form method="get" asp-action="GetAllComments" asp-controller="Comment">

        <input id="searchParam" name="searchParam" type="text" value="" />
        <input type="submit" value="Search" />
    </form>
    <a href="~/Comment/GetAllComments">Refresh</a>
    <h1>Comments</h1>
    <table class="table">
        <tr><th>Id Comment</th><th>Title</th><th>Description</th><th>Img</th><th>Option</th></tr>
        @foreach (Comment u in Model.Items)
        {
            <tr>
                <td>@u.CommentsId</td>
                <td>
                    @u.Title
                </td>
                <td>
                    @u.Description
                </td>
                <td>
                    <img style='width:80%; height:60%;' src="data:image/jpeg;base64,@(Convert.ToBase64String(u.Img.ImageData))" />
                </td>
                <td>
                    <div style="border:dotted">
                        <form method="post" asp-action="PutComment" asp-controller="Comment">
                            <h2>Put Comment</h2>
                            <input id="CommentsId" name="CommentsId" type="hidden" value="@u.CommentsId" />
                            <label>Title</label><br />
                            <input type="text" name="Title" /><br />
                            <label>Description</label><br />
                            <input type="text" name="Description" /><br />
                            <label>Img</label>
                            <div class="dropDownList"></div><br />
                            <input type="submit" value="Put" />
                        </form>

                    </div>
                    <a href="/Comment/Delete/@u.CommentsId">Delete</a>
                </td>
            </tr>
        }
    </table>
    @if (Model.PageViewModel.HasPreviousPage)
    {
        <a asp-action="GetAllComments"
           asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
           class="btn btn-outline-dark">
            <i class="glyphicon glyphicon-chevron-left"></i>
            back
        </a>
    }
    @if (Model.PageViewModel.HasNextPage)
    {
        <a asp-action="GetAllComments"
           asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
           class="btn btn-outline-dark">
            next
            <i class="glyphicon glyphicon-chevron-right"></i>
        </a>
    }
</div>
<div style="margin:20px;border:dotted">
    <form method="post" asp-action="PostComment" asp-controller="Comment">
        <h2>Post Comment</h2>
        <label>Title</label><br />
        <input type="text" name="Title" /><br />
        <label>Description</label><br />
        <input type="text" name="Description" /><br />
        <label>Img</label>
        <div class="dropDownList"></div><br />
        <input type="submit" value="Post" />
    </form>
    <script>
        GetAllId()
        async function GetAllId() {
            let url = "/Img"
            let response = await fetch(url + "/GetAllID");
            if (response.ok) {
                let data = await response.json();
                let html = "<select id='ImgsId' name='ImgsId' is='ms-dropdown' style='width: 300px;'>"
                if (Array.isArray(data)) {

                    data.forEach(r => {
                        html += "<option id='ImgsId' name='ImgsId' value='" + r + "' data-image=' " + url + "/GetImage/" + r + "'></option>"
                    })
                } else {
                    html += "<option value='" + data + "' data-image=' " + url + "/GetImage/" + data + "'></option>"
                }
                html += "</select>"

                document.querySelectorAll(".dropDownList").forEach(r =>
                    r.innerHTML = html
                )
            } else {
                alert("Ошибка HTTP: " + response.status);
            }
        }
    </script>
</div>

TestWebApplication/TestWebApplication/Pages/Shared/ViewAllImg.cshtml
@using TestWebApplication.Models
@model IndexViewModel<Img>


<div style="margin:20px;border:dotted">
    <p>Check the box if you want to remove more than one</p>
    <h1>Imgs</h1>
    <table class="table">
        <tr><th>Id img</th><th>Img</th><th>Option</th></tr>
        @foreach (Img u in Model.Items)
        {
            <tr>
                <td>@u.ImgsId</td>
                <td>
                    <img style='width:80px; height:60px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(u.ImageData))" />
                </td>
                <td>
                    <div style="border:dotted">
                        <form method="post" asp-action="PutImg" asp-controller="Img" enctype="multipart/form-data">
                            <h5>Put Img</h5>
                            <input id="ImgsId" name="ImgsId" type="hidden" value="@u.ImgsId" />
                            <input type="file" name="ImageData" /><br>
                            <input type="submit" value="Put" />
                        </form>
                    </div>
                    <div>
                        <input type="checkbox" class="checkbox" style="margin:14px" name="@u.ImgsId" value="@u.ImgsId"><Br>
                    </div>
                    <a href="/Img/Delete/@u.ImgsId">Delete</a>
                </td>
            </tr>
        }
    </table>
    @if (Model.PageViewModel.HasPreviousPage)
    {
        <a asp-action="GetAllImgs"
           asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
           class="btn btn-outline-dark">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Назад
        </a>
    }
    @if (Model.PageViewModel.HasNextPage)
    {
        <a asp-action="GetAllImgs"
           asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
           class="btn btn-outline-dark">
            Вперед
            <i class="glyphicon glyphicon-chevron-right"></i>
        </a>
    }
</div>

<div style="margin:20px;border:dotted">
    <form method="post" asp-action="PostImg" asp-controller="Img" enctype="multipart/form-data">
        <h2>Post Img</h2>
        <input type="file" name="ImageData" /><br>
        <input type="submit" value="Post" />
    </form>
</div>
<div style="margin:20px;border:dotted">
    <form method="post" asp-action="PostImport" asp-controller="Img" enctype="multipart/form-data">
        <h2>Import</h2>
        <input type="file" name="file" /><br>
        <input type="submit" value="Import" />
    </form>
</div>
<div style="margin:20px;border:dotted">
    <form method="post" asp-action="PostExport" asp-controller="Img" enctype="multipart/form-data">
        <h2>Export</h2>
        <input type="submit" value="Export" />
    </form>
</div>
<div style="margin:20px;border:dotted">
    <input type="button" onclick="Delete()" value="Detele mote than one" />
</div>

<script>
    function getCheckedCheckBoxes() {
        var checkboxes = document.getElementsByClassName('checkbox');
        var checkboxesChecked = [];
        for (var index = 0; index < checkboxes.length; index++) {
            if (checkboxes[index].checked) {
                checkboxesChecked.push(parseInt(checkboxes[index].value));
            }
        }
        return checkboxesChecked;
    }
    async function Delete() {
        let url ="/Img"
        console.log(getCheckedCheckBoxes())
        await fetch(url + "/DeleteArrayItems", {
            method: 'Delete',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ Items: getCheckedCheckBoxes() })
        })
        window.location.href = url + "/GetAllImgs"
    }
</script>

TestWebApplication/TestWebApplication/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="~/lib/ms-Dropdown-master/dist/js/dd.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/lib/ms-Dropdown-master/dist/css/dd.css" />
    <style>
        @@font-face {
            font-family: 'FontAwesome';
            src: url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2') format('woff2'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff') format('woff'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf') format('truetype');
            font-weight: normal;
            font-style: normal
        }

        .glyphicon {
            display: inline-block;
            font: normal normal normal 14px/1 FontAwesome;
            font-size: inherit;
            text-rendering: auto;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale
        }

        .glyphicon-chevron-right:before {
            content: "\f054";
        }

        .glyphicon-chevron-left:before {
            content: "\f053";
        }
    </style>
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>